### ISSUE TITLE
提示没这成员 output_names.push_back(ort_session->GetOutputName(i, allocator));

### ISSUE THREAD

**Issue by icyfox168168** [hpc203/PaddleOCR-v3-onnxrun-cpp-py#1]
GetOutputName 如何解决

**Comment by hpc203** [comment]
> GetOutputName

这种问题百度一下就能找到答案的呀
https://blog.csdn.net/weixin_46068431/article/details/127970798
参考这个文章里的解决办法

**Comment by icyfox168168** [comment]
ok 感谢分享如此好的源码
